#Desafio da ula 06

something = input('Digite algo: ')
tipo = type(something)
inf = something.isalpha()
inf2 = something.isnumeric()
inf3 = something.isalnum()
inf4 = something.isupper()
inf5 = something.islower()
inf6 = something.isdecimal()
inf7 = something.isspace()
inf8 = something.isdigit()
inf9 = something.isprintable()
inf10 = something.istitle()
inf11 = something.isascii()
inf12 = something.isidentifier()

print("o elemento {} digitado é: \n".format(something))
print("Do tipo: {}".format(tipo))
print("Letra? - {}".format(inf))
print("Número? - {}".format(inf2))
print("É número com letra? - {}".format(inf3))
print("Está somente em letras maíusculas? - {}".format(inf4))
print("Está somente em letras minúsculas? - {}".format(inf5))
print("É decimal? - {}".format(inf6))
print("É um espaço? - {}".format(inf7))
print("É um digito? - {}".format(inf8))
print("É imprimível? - {}".format(inf9))
print("É um título? - {}".format(inf10))
print("Está no padrão ASCII? - {}".format(inf11))
print("É um identificador? - {}".format(inf12))
